url: "https://charli-faerie.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Charli" # the name of your site, e.g. ACME Corp.
lang: en-GB
exclude: 
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  - "postcss.config.js"
  - "tailwind.config.js"
  - "README.md"
  - "assets/css/tailwind.css"
  - drafts
  - node_modules